### ISSUE TITLE
Fix the code base + support reading HTTP headers.

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csvw-check#77]
There are 3 test scenarios failing as of now since we do not process this information.

Headers while fetching the csv (source url) must be processed.

https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#link-header

**Comment by mikeAdamss** [comment]
Made some progress before getting retasked, progress on this branch: https://github.com/GSS-Cogs/csvw-check/tree/issue-77/headers

The `ISSUE77.md` file has some high level information about what I did thus far and why.
